[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tennis"
version = "0.0.1"
description = "The Tennis Kata"
requires-python = ">=3.12"

[tool.setuptools]
py-modules = ["tennis1", "tennis2", "tennis3", "tennis4"]
