[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tennis"
version = "1.0.0"

[tool.pytest.ini_options]
python_classes = "~"
python_functions = "~"
