[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "karate_chop"
version = "0.0.1"
description = "The Karate Chop Kata"
requires-python = ">=3.12"

[tool.setuptools]
py-modules = ["karate_chop"]
