[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "audit_everything"
version = "0.0.1"
description = "The Audit Everything Kata"
requires-python = ">=3.11"

[tool.setuptools]
py-modules = ["audit_everything"]
